### ISSUE TITLE
Přidání kontroly na připojené externí přihlášení

### ISSUE THREAD

**Issue by motirek** [SW22-Testing/automatic-testing#37]
**Popis úpravy/nové funkce**
> Kontrola před přidáním externího přihlášení

**Proč vytvořit**
- Jinak se musí dělat manuální odstranění ex. přihlášení, pokud spadne/neprojde test

**Comment by motirek** [comment]
Prozatím jen pro Microsoft. Metodu udelat v lokalni tride (PrihlaseniOdhlaseni.cs)

**Comment by Twinrest** [comment]
Již vyřešeno #38 uzavírám tento issue
