### ISSUE TITLE
Přidání kontroly pro existující microsoft

### ISSUE THREAD

**Issue by motirek** [SW22-Testing/automatic-testing#38]
**Popis úpravy/nové funkce**
> Přidání kontroly jestli existuje externí přihlášení microsoft.

**Proč vytvořit**
- Když existuje tak se smaže aby nedocházelo k pádům

**Comment by motirek** [comment]
prozatím jen pro Microsoft

**Comment by Twinrest** [comment]
Upravil jsem to ať se ví o co tady jde

**Comment by Twinrest** [comment]
Přidal jsem tam i ten wait na tom loginu a funguje mi to tak to potom zkus

**Comment by Twinrest** [comment]
V tomto issue se mi i povedlo opravit google přihlášení

**Comment by Twinrest** [comment]
Neboj míro dodělám to jakmile bude čas :D

**Comment by motirek** [comment]
Opravena kontrola

> Možná změna kontroly (nebude metoda)

Nefunguje google

**Comment by Twinrest** [comment]
Ti dám nefunguje google
